version: '3.4'

services:
  ruby-base:
    &ruby-base
    build:
      dockerfile: docker/Dockerfile-ruby
      context: .
    volumes:
      - ./:/code

  ruby-dev:
    <<: *ruby-base
    command: bash

  go-base:
    &go-base
    build:
      dockerfile: docker/Dockerfile-go
      context: .
    volumes:
      - ./:/go/src/code/

  go-dev:
    <<: *go-base
    command: bash

