version: '3.4'

x-default-args:
  &default-args
  args:
    - EXERCISM_TOKEN=${EXERCISM_TOKEN}

services:
  ruby-base:
    &ruby-base
    build:
      dockerfile: docker/Dockerfile-ruby
      context: .
      <<: *default-args
    volumes:
      - ./:/code

  ruby-dev:
    <<: *ruby-base
    command: bash

  go-base:
    &go-base
    build:
      dockerfile: docker/Dockerfile-go
      context: .
      <<: *default-args
    volumes:
      - ./:/go/src/code/

  go-dev:
    <<: *go-base
    command: bash

