FROM ruby:3.2-rc-buster

COPY ./docker/install_exercism.sh /code/

WORKDIR /code

RUN /code/install_exercism.sh
RUN gem install rubocop

ARG EXERCISM_TOKEN
ENV EXERCISM_TOKEN=${EXERCISM_TOKEN}
RUN exercism configure -t $EXERCISM_TOKEN
